config/routes.rb
Rails.application.routes.draw do
    root 'homes#index'
    get '/users/dashboard', to: 'users#dashboard'
    get '/users/profile', to: 'users#profile'
    resources :cards, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :transactions, only: [:index, :show, :new, :create]
    resources :users, only: [:index, :show, :new, :create, :update]
    resources :sessions, only: [:new, :create, :destroy]
  	resources :relations, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/relation.rb
class Relation < ApplicationRecord
	validates :follower, uniqueness: { scope: :followed }
	validate :cant_follow_yourself

	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	private

	  	def cant_follow_yourself
	    	if follower == followed
	    		errors.add(:what, "You cannot follow yourself!")
	    	end
	  	end

end

app/models/transaction.rb
class Transaction < ApplicationRecord

	validates :amount, presence: true, numericality: {greater_than: 0}
	validate :amount_not_higher_than_balance
	validate :self_transaction

	belongs_to :sender, class_name: "User"
	belongs_to :receiver, class_name: "User"

	def amount_not_higher_than_balance
		if self.sender.balance < self.amount
			errors.add(:amount, "Not enough funds in balance")
		end
	end

	def self_transaction
		if self.sender == self.receiver
			errors.add(:Nope, "You can't send money to yourself")
		end
	end


end

app/models/user.rb
class User < ApplicationRecord
	validates_uniqueness_of :username

	has_many :sent_transactions, class_name: "Transaction", foreign_key: "sender_id"
	has_many :received_transactions, class_name: "Transaction", foreign_key: "receiver_id"
	has_many :cards
	has_many :followers, class_name: "Relation", foreign_key: "follower_id"
	has_many :followeds, class_name: "Relation", foreign_key: "followed_id"

	has_secure_password

	def follows
		self.followers.map {|relation| relation.followed}
	end

	def fans
		self.followeds.map {|relation| relation.follower}
	end

	def receivers
		self.sent_transactions.map {|trans| trans.receiver}
	end

	def senders
		self.received_transactions.map {|trans| trans.sender}
	end

	def withdraw(amount)
		current_balance = self.balance
		self.update(balance: current_balance - amount)
	end

	def deposit(amount)
		current_balance = self.balance
		self.update(balance: current_balance + amount)
	end

	def self.search(search)
	  if search
	  	w = search.downcase
	    User.where("LOWER(username) LIKE ? OR LOWER(name) LIKE ?", "%#{w}%", "%#{w}%")
	  else
	    User.all
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :setup_global_errors, :setup_user_stuff

  private

  def log_in!(user)
    session[:user_id] = user.id
  end

  def setup_global_errors
    @errors = flash[:errors]
  end

  def logged_in?
    !!session[:user_id]
  end

  def setup_user_stuff
    if session["user_id"]
      @logged_in_user = User.find(session["user_id"])
      sql = "select count(*) from (select followed_id from relations f where f.follower_id = #{session["user_id"].to_i} UNION select follower_id from relations f where f.followed_id = #{session["user_id"].to_i})as a"
      @friendships = ActiveRecord::Base.connection.execute(sql).getvalue(0,0)
    end
  end

  def authenticate
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	before_action :authenticate

	def index
		@cards = @logged_in_user.cards
	end

	def new
		@card = Card.new
	end

	def create
		@c = Card.new(card_params)
		@c.user = @logged_in_user
		if @c.save
		  redirect_to cards_path
		else
		  flash[:errors] = @c.errors.full_messages
		  redirect_to new_card_path
		end
	end

	def edit
		@card = Card.find(params[:id])
	end

	def update
		@card = Card.find(params[:id])
		if @card.update(card_params)
		  redirect_to cards_path
		else
		  flash[:errors] = @card.errors.full_messages
		  render :edit
		end
	end

	def destroy
		@card_id = params[:id]
		Card.destroy(@card_id)
		redirect_to cards_path
	end

	private

	def card_params
		params.require(:card).permit(:card_number, :security_code, :exp_date, :zip_code, :card_type)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
  	end
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
	before_action :authenticate

	def index
		@followers = @logged_in_user.fans
		@followings = @logged_in_user.follows
	end

	def create
    	@user = User.find(relation_params[:format])
    	@relation = Relation.new(follower: @logged_in_user, followed: @user)
		    if @relation.save
		      redirect_back fallback_location: root_path
		    else
		      flash[:errors] = @relation.errors.full_messages
		      redirect_back fallback_location: root_path
		    end
  	end

  	def destroy
  		@user = User.find(relation_id_params[:id])
		@r = Relation.find_by(follower: @logged_in_user, followed: @user)
		@r.destroy
		redirect_back fallback_location: root_path
	end

  	private

  	def relation_params
		params.permit(:format)
  	end

  	def relation_id_params
		params.permit(:id)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end


  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      log_in!(@user)
      redirect_to users_dashboard_path
    else
      flash[:errors] = ["Invalid Credentials"]
      redirect_to new_session_path
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
before_action :authenticate
	def index
		 @my_sent = @logged_in_user.sent_transactions.sort_by {|t| t.created_at.to_i * -1}
		 @my_received = @logged_in_user.received_transactions.sort_by {|t| t.created_at.to_i * -1}
	end

	def new
		@transaction = Transaction.new
		@all_users = User.all
	end

	def create
		@receiver = User.find(transaction_params[:receiver])
		@amount = transaction_params[:amount].to_d
		@message = transaction_params[:message]
		@t = Transaction.new(sender: @logged_in_user, receiver: @receiver, amount: @amount, message: @message)
		if @t.valid?
			Transaction.transaction do
				@t.save
				@logged_in_user.withdraw(@amount)
				@receiver.deposit(@amount)
			end
			redirect_to transactions_path
		else
			flash[:errors] = @t.errors.full_messages
		  	redirect_to new_transaction_path
		end
	end

	private

	def transaction_params
		params.require(:transaction).permit(:receiver, :amount, :message)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		authenticate
		@users = User.search(params[:search])
		if @users.empty?
			@errors = ["Whoops!, no user matches your search"]
		end
	end

	def new
    	@user = User.new
  	end

	def create
		@user = User.new(user_params)
		if @user.save
		  log_in!(@user)
		  redirect_to users_dashboard_path
		else
		  flash[:errors] = @user.errors.full_messages
		  redirect_to new_user_path
		end
	end

	def dashboard
		authenticate
		@transactions = Transaction.all.sort_by {|t| t.created_at.to_i * -1}
	end

	def profile
		authenticate
	end

	def update
		@name = user_edit_params[:name]
		@email = user_edit_params[:email]
		uploaded_io = user_edit_params[:image]
		if uploaded_io
			ext = File.extname(uploaded_io.original_filename)
			filename = "#{@logged_in_user.username}#{ext}"
			File.open(Rails.root.join('app', 'assets', 'images', filename), 'wb') do |file|
		  		file.write(uploaded_io.read)
			end
			@logged_in_user.update(image: filename)
		end

		if @logged_in_user.update(name: @name, email: @email, image: filename)
		  	redirect_to users_profile_path
		else
		  	flash[:errors] = @c.errors.full_messages
		  	render :edit
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :username, :password, :password_confirmation)
	end

	def user_edit_params
		params.require(:user).permit(:name, :email, :image)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/edit.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Add a new card</h5>
            <%= form_for @card, :html => {:class => "form-signin"} do |f| %>
              <div class="form-label-group">
                <%= f.text_field :card_number, class:"form-control", required:""  %>
                <%= f.label :card_number %>
              </div>
              <div class="form-label-group">
                <%= f.text_field :card_type, class:"form-control", required:""  %>
                <%= f.label :card_type %>
              </div>
              <div class="form-label-group">
                <%= f.text_field :exp_date, :value => @card.exp_date.strftime("%m/%Y"),class:"form-control", required:"", min: Date.today  %>
                <%= f.label "expiration date" %>
              </div>
              <div class="form-label-group">
                <%= f.text_field :security_code, class:"form-control", required:""  %>
                <%= f.label :security_code %>
              </div>
              <div class="form-label-group">
                <%= f.text_field :zip_code, class:"form-control", required:""  %>
                <%= f.label :zip_code %>
              </div>
              <%= f.submit "Add card", class:"btn btn-lg btn-primary btn-block text-uppercase"%>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/cards/index.html.erb
<div class="container">
	<div class="col center-block p-3">
		<h1>Your cards</h1>
	</div>
	<div class="col-md-12 text-center">
		<%= link_to "<button class='btn btn-primary'>+ Add Card</button>".html_safe, new_card_path %>
	</div>
	<div class="row p-3">
		<% @cards.each do |card| %>
		<div class="card col-md-4 p-2 mx-auto">
		  <div class="card-body">
		    <h5 class="card-title"><%= card.user.name %></h5>
		    <h6 class="card-subtitle mb-2 text-muted"><%= card.card_type %></h6>
		    <p class="card-text"><%= "ending in: #{card.card_number[-4..-1]}" %></p>
		    <p class="card-text"><%= "Expires: #{card.exp_date.strftime("%m/%Y")}" %></p>
		    <%= link_to("Edit Card", edit_card_path(card) , class:"card-link") %>
		    <%= link_to("Delete Card", card_path(card), class:"card-link", method:"delete") %>
		  </div>
		</div>
		<% end %>
	</div>
</div>

app/views/cards/new.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Add a new card</h5>
            <%= form_for @card, :html => {:class => "form-signin"} do |f| %>
              <div class="form-label-group">
                <%= f.text_field :card_number, class:"form-control", required:""  %>
                <%= f.label :card_number %>
              </div>
              <div class="form-label-group">
                <%= f.text_field :card_type, class:"form-control", required:""  %>
                <%= f.label :card_type %>
              </div>
              <div class="form-label-group">
                <%= f.date_field :exp_date, class:"form-control", required:"", min: Date.today %>
                <%= f.label "expiration date" %>
              </div>
              <div class="form-label-group">
                <%= f.text_field :security_code, class:"form-control", required:""  %>
                <%= f.label :security_code %>
              </div>
              <div class="form-label-group">
                <%= f.text_field :zip_code, class:"form-control", required:""  %>
                <%= f.label :zip_code %>
              </div>
              <%= f.submit "Add card", class:"btn btn-lg btn-primary btn-block text-uppercase"%>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/homes/index.html.erb
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h4 class="masthead-subheading mb-0">Send money at beak speeds</h4>
      <h1 class="masthead-heading mb-3">Pidgeon</h1>
      <h6 class="masthead-subheading mb-0">Join now and get <strong>$500</strong> on us</h6>
      <a href="#pid" class="btn btn-primary btn-xl rounded-pill mt-5">Learn More</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>

<section>
  <div class="container" id="pid">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <%= image_tag "pigeon_money.png", class:"img-fluid rounded-circle" %>
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Make instant payments</h2>
          <p>The Pidgeon™ engine was designed using state of the art tools, allowing our servers to handle millions of transactions each second.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <%= image_tag "pidgeon_secure.jpg", class:"img-fluid rounded-circle" %>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">Secure Transfers</h2>
          <p>Military grade encryption help us maintain anonimity and irreversibility on any transaction.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container" id="pid">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <%= image_tag "pidgeon_friends.jpg", class:"img-fluid rounded-circle" %>
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Share with friends</h2>
          <p>Let everyone know who you are sending money to!</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pidgeon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  </head>
  <body>
    <nav class="navbar navbar-light navbar-expand-md navigation-clean-button fixed-top">
      <a href="/" class="navbar-brand"><%= image_tag "logo.jpg", width: "80" %>Pidgeon</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <span class="navbar-text actions">
            <% if @logged_in_user %>
            <div class="dropdown">
              <%= link_to(image_tag(@logged_in_user.image || "default.jpg", width:"35", class:"rounded-circle mx-auto"), users_profile_path) %>
              <button class="btn btn-primary dropdown-toggle mx-3" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= "@#{@logged_in_user.username}" %>
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to("Balance: $#{'%.2f' % @logged_in_user.balance.to_f}", users_dashboard_path, :class=>"login dropdown-item") %>
                <%= link_to("Cards", cards_path, :class=>"login dropdown-item") %>
                <%= link_to("Friends #{@friendships}", relations_path, :class=>"login dropdown-item") %>
                <%= link_to("Transactions", transactions_path, :class=>"login dropdown-item") %>
              </div>
            <%= link_to("Log Out", "/sessions/#{@logged_in_user.id}", :class=>"login", method: "delete") %>
            </div>
            <% else %>
            <%= link_to("Log In", new_session_path, { :class=>"login" }) %>
            <%= link_to("Sign Up", new_user_path, { :class=>"btn btn-primary action-button", :role=>"button" }) %>
            <% end %>
          </span>
        </ul>
      </div>
    </nav>
    <%= yield %>
    <% if @errors %>
      <ul class="errors">
          <% @errors.each do |error| %>
              <%= error %>
          <% end %>
      </ul>
    <% end %>
    <div class="footer-basic">
        <footer>
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="/">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">Pidgeon © 2019</p>
        </footer>
    </div>
  </body>
</html>

app/views/relations/index.html.erb
<div class="container">
	<div class="col center-block p-3">
		<h1>Friends</h1>
	</div>
	<div class="col-md-12 text-center mb-3">
		<%= link_to "<button class='btn btn-primary'>Add more friends! 😄🎉</button>".html_safe, users_path %>
	</div>
	<div class="row">
		<div class="col-md-6 mx-auto">
			<h2 class="p-3 text-center">Followers <%= @followers.count %></h2>
			<% @followers.each do |f| %>
				<div class="card p-1">
				  <div class="card-body row p-2">
			  		<div class="col-sm-3 p-2 text-center">
						<%= image_tag f.image, class:"img-fluid rounded-circle mx-auto d-block", width:"90px" %>
					</div>
					<div class="col-sm-7 p-1">
						<div class="col-sm-12 p-1 mr-1">
					    	<h6 class="card-title"><%= f.username %></h6>
					    	<p class="card-text m-0"><%= f.name %></p>
					    	<p class="hour"><%= "Joined Pidgeon #{time_ago_in_words(f.created_at)} ago" %></p>
					    </div>
					</div>
				    <div class="col-sm-2 p-1 text-center">
				    	<a href="#"><i class="icon ion-heart"></i></a>
					</div>
				  </div>
				</div>
			<% end %>
		</div>
		<div class="col-md-6 mx-auto">
			<h2 class="p-3 text-center">Following <%= @followings.count %></h2>
			<% @followings.each do |f| %>
				<div class="card p-1">
				  <div class="card-body row p-2">
			  		<div class="col-sm-3 p-2 text-center">
						<%= image_tag f.image, class:"img-fluid rounded-circle mx-auto d-block", width:"90px" %>
					</div>
					<div class="col-sm-7 p-1">
						<div class="col-sm-12 p-1 mr-1">
					    	<h6 class="card-title"><%= f.username %></h6>
					    	<p class="card-text m-0"><%= f.name %></p>
					    	<p class="hour"><%= "Joined Pidgeon #{time_ago_in_words(f.created_at)} ago" %></p>
					    </div>
					</div>
				    <div class="col-sm-2 p-1 text-center">
				    	<a href="#"><i class="icon ion-heart"></i></a>
					</div>
				  </div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/transactions/index.html.erb
<div class="container">
	<div class="col center-block p-3">
		<h1>My Transactions</h1>
	</div>
	<div class="col-md-12 text-center mb-3">
		<%= link_to "<button class='btn btn-primary'>Send Money 💸</button>".html_safe, new_transaction_path %>
	</div>
	<div class="row">
		<div class="col-md-6 mx-auto">
			<h2 class="p-3 text-center">Sent</h2>
			<% @my_sent.each do |t| %>
				<div class="card p-1">
				  <div class="card-body row p-2">
			  		<div class="col-sm-3 p-2 text-center">
						<%= image_tag t.sender.image, class:"img-fluid rounded-circle mx-auto d-block", width:"90px" %>
					</div>
					<div class="col-sm-7 p-1">
						<div class="col-sm-12 p-1 mr-1">
					    	<h6 class="card-title"><%= "You paid $#{'%.2f' % t.amount.to_f} to #{t.receiver.name}" %></h6>
					    	<p class="card-text m-0"><%= t.message %></p>
					    	<p class="hour"><%= "#{time_ago_in_words(t.created_at)} ago" %></p>
					    </div>
					</div>
				    <div class="col-sm-2 p-1 text-center">
				    	<a href="#"><i class="icon ion-heart"></i></a>
					</div>
				  </div>
				</div>
			<% end %>
		</div>
		<div class="col-md-6 mx-auto">
			<h2 class="p-3 text-center">Received</h2>
			<% @my_received.each do |t| %>
				<div class="card p-1">
				  <div class="card-body row p-2">
			  		<div class="col-sm-3 p-2 text-center">
						<%= image_tag t.sender.image, class:"img-fluid rounded-circle mx-auto d-block", width:"90px" %>
					</div>
					<div class="col-sm-7 p-1">
						<div class="col-sm-12 p-1 mr-1">
					    	<h6 class="card-title"><%= "#{t.sender.name} paid you $#{'%.2f' % t.amount.to_f}" %></h6>
					    	<p class="card-text m-0"><%= t.message %></p>
					    	<p class="hour"><%= "#{time_ago_in_words(t.created_at)} ago" %></p>
					    </div>
					</div>
				    <div class="col-sm-2 p-1 text-center">
				    	<a href="#"><i class="icon ion-heart"></i></a>
					</div>
				  </div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/transactions/new.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Send Money 💵</h5>
            <%= form_for @transaction, :html => {:class => "form-signin"} do |f| %>
              <div class="form-label-group">
                <h6>To:</h6>
                <%= f.collection_select :receiver, @all_users, :id, :username, {}, {:class=>"form-control"} %>
              </div>
              <div class="form-label-group">
                <h6>Amount in $</h6>
                <%= f.number_field :amount, class:"form-control", required:"", :step => 0.01  %>
              </div>
              <div class="form-label-group">
                <h6>Write a message</h6>
                <%= f.text_field :message, class:"form-control", required:""  %>
              </div>
                <%= f.submit "Pay now!", class:"btn btn-lg btn-primary btn-block text-uppercase"%>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/users/dashboard.html.erb
<div class="container">
	<div class="col center-block p-3">
		<h1>Welcome <%= @logged_in_user.name.split(' ')[0] %></h1>
	</div>
	<div class="col-md-12 text-center mb-3">
		<%= link_to "<button class='btn btn-primary'>Send Money 💸</button>".html_safe, new_transaction_path %>
	</div>
	<div class="row">
		<div class="col-md-12 mx-auto">
			<h2 class="p-3 text-center">Happening now!</h2>
			<% @transactions.each do |t| %>
				<div class="card p-1">
				  <div class="card-body row p-2">
			  		<div class="col-sm-3 p-2 text-center">
						<%= image_tag t.sender.image, class:"img-fluid rounded-circle mx-auto d-block", width:"90px" %>
					</div>
					<div class="col-sm-7 p-1">
						<div class="col-sm-12 p-1 mr-1">
					    	<h6 class="card-title"><%= "#{t.sender.name} paid #{t.receiver.name}" %></h6>
					    	<p class="card-text m-0"><%= t.message %></p>
					    	<p class="hour"><%= "#{time_ago_in_words(t.created_at)} ago" %></p>
					    </div>
					</div>
				    <div class="col-sm-2 p-1 text-center">
				    	<a href="#"><i class="icon ion-heart"></i></a>
					</div>
				  </div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="col center-block p-3">
		<h1>Search friends!</h1>
	</div>
	<%= form_tag users_path, :method => 'get' , class:"form-inline justify-content-center mb-5" do %>
		<%= text_field_tag :search, params[:search], class:"form-control mr-sm-2" %>
		<%= submit_tag "Search", :name => nil, class:"btn btn-outline-primary my-2 my-sm-0" %>
	<% end %>
	<div class="row">
		<div class="col-md-12 mx-auto">
			<% @users.each do |u| %>
				<div class="card p-1">
				  <div class="card-body row p-2">
			  		<div class="col-sm-3 p-2 text-center">
						<%= image_tag u.image, class:"img-fluid rounded-circle mx-auto d-block", width:"90px" %>
					</div>
					<div class="col-sm-7 p-1">
						<div class="col-sm-12 p-1 mr-1">
					    	<h6 class="card-title"><%= "@#{u.username}" %></h6>
					    	<p class="card-text m-0"><%= u.name %></p>
					    	<p class="hour"><%= "Joined Pidgeon#{time_ago_in_words(u.created_at)} ago" %></p>
					    </div>
					</div>
				    <div class="col-sm-2 p-1 text-center">
				    	<a href="#"><i class="icon ion-heart"></i></a>
				    	<% if @logged_in_user.follows.include?(u) %>
				    		<%= link_to("<button class='btn btn-secondary'>Following</button>".html_safe, relation_path(u), class:"card-link", method:"delete") %>
				    	<% else %>
				    		<%= link_to("<button class='btn btn-primary'>Follow</button>".html_safe, relations_path(u), class:"card-link", method:"post") %>
				    	<% end %>
					</div>
				  </div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Sign Up</h5>
            <%= form_for @user, :html => {:class => "form-signin"} do |f| %>
              <div class="form-label-group">
                <%= f.text_field :name, class:"form-control", required:""  %>
                <%= f.label :name %>
              </div>
              <div class="form-label-group">
                <%= f.text_field :username, class:"form-control", required:""  %>
                <%= f.label :username %>
              </div>
              <div class="form-label-group">
                <%= f.password_field :password, class:"form-control", required:""  %>
                <%= f.label :password %>
              </div>
              <div class="form-label-group">
                <%= f.password_field :password_confirmation, class:"form-control", required:""  %>
                <%= f.label :password_confirmation %>
              </div>
              <%= f.submit "Sign Up", class:"btn btn-lg btn-primary btn-block text-uppercase"%>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/users/profile.html.erb
<div class="container">
  <div class="col center-block p-3">
    <h1>Profile</h1>
  </div>
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <%= form_for @logged_in_user, :html => {:class => "form-signin"} do |f| %>
            <div class="form-label-group">
              <%= image_tag(@logged_in_user.image || "default.jpg", class:"img-fluid rounded-circle mx-auto d-block", width: "140px") %>
            </div>
            <div class="form-label-group">
              <%= f.file_field :image, class:"form-control" %>
            </div>
            <div class="form-label-group">
              <%= f.text_field :name, class:"form-control", required:""  %>
              <%= f.label :name %>
            </div>
            <div class="form-label-group">
              <%= f.text_field :email, class:"form-control"  %>
              <%= f.label :email %>
            </div>
            <%= f.submit "Save", class:"btn btn-lg btn-primary btn-block text-uppercase"%>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>